CTFd/utils/user/__init__.py
from flask import current_app as app, session, request
from CTFd.models import Users
from CTFd.utils import get_config
from CTFd.models import db, Fails
import datetime
import re


def get_current_user():
    if authed():
        user = Users.query.filter_by(id=session["id"]).first()
        return user
    else:
        return None


def get_current_team():
    if authed():
        user = get_current_user()
        return user.team
    else:
        return None


def authed():
    return bool(session.get("id", False))


def is_admin():
    if authed():
        return session["type"] == "admin"
    else:
        return False


def is_verified():
    if get_config("verify_emails"):
        user = get_current_user()
        if user:
            return user.verified
        else:
            return False
    else:
        return True


def get_ip(req=None):
    """ Returns the IP address of the currently in scope request. The approach is to define a list of trusted proxies
     (in this case the local network), and only trust the most recently defined untrusted IP address.
     Taken from http://stackoverflow.com/a/22936947/4285524 but the generator there makes no sense.
     The trusted_proxies regexes is taken from Ruby on Rails.

     This has issues if the clients are also on the local network so you can remove proxies from config.py.

     CTFd does not use IP address for anything besides cursory tracking of teams and it is ill-advised to do much
     more than that if you do not know what you're doing.
    """
    if req is None:
        req = request
    trusted_proxies = app.config["TRUSTED_PROXIES"]
    combined = "(" + ")|(".join(trusted_proxies) + ")"
    route = req.access_route + [req.remote_addr]
    for addr in reversed(route):
        if not re.match(combined, addr):  # IP is not trusted but we trust the proxies
            remote_addr = addr
            break
    else:
        remote_addr = req.remote_addr
    return remote_addr


def get_wrong_submissions_per_minute(account_id):
    """
    Get incorrect submissions per minute.

    :param account_id:
    :return:
    """
    one_min_ago = datetime.datetime.utcnow() + datetime.timedelta(minutes=-1)
    fails = (
        db.session.query(Fails)
        .filter(Fails.account_id == account_id, Fails.date >= one_min_ago)
        .all()
    )
    return len(fails)

CTFd/views.py
from flask import (
    current_app as app,
    render_template,
    request,
    redirect,
    abort,
    url_for,
    session,
    Blueprint,
    Response,
    send_file,
)
from flask.helpers import safe_join

from CTFd.models import db, Users, Admins, Teams, Files, Pages, Notifications
from CTFd.utils import markdown
from CTFd.cache import cache
from CTFd.utils import get_config, set_config
from CTFd.utils.user import authed, get_current_user
from CTFd.utils import config
from CTFd.utils.uploads import get_uploader
from CTFd.utils.config.pages import get_page
from CTFd.utils.config.visibility import challenges_visible
from CTFd.utils.security.auth import login_user
from CTFd.utils.security.csrf import generate_nonce
from CTFd.utils import user as current_user
from CTFd.utils.dates import ctftime, ctf_ended, view_after_ctf
from CTFd.utils.decorators import authed_only
from CTFd.utils.security.signing import (
    unserialize,
    BadTimeSignature,
    SignatureExpired,
    BadSignature,
)
from sqlalchemy.exc import IntegrityError
import os


views = Blueprint("views", __name__)


@views.route("/setup", methods=["GET", "POST"])
def setup():
    if not config.is_setup():
        if not session.get("nonce"):
            session["nonce"] = generate_nonce()
        if request.method == "POST":
            ctf_name = request.form["ctf_name"]
            set_config("ctf_name", ctf_name)

            # CSS
            set_config("start", "")

            # Admin user
            name = request.form["name"]
            email = request.form["email"]
            password = request.form["password"]
            admin = Admins(
                name=name, email=email, password=password, type="admin", hidden=True
            )

            user_mode = request.form["user_mode"]

            set_config("user_mode", user_mode)

            # Index page

            index = """<div class="row">
    <div class="col-md-6 offset-md-3">
        <img class="w-100 mx-auto d-block" style="max-width: 500px;padding: 50px;padding-top: 14vh;" src="themes/core/static/img/logo.png" />
        <h3 class="text-center">
            <p>A cool CTF platform from <a href="https://ctfd.io">ctfd.io</a></p>
            <p>Follow us on social media:</p>
            <a href="https://twitter.com/ctfdio"><i class="fab fa-twitter fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://facebook.com/ctfdio"><i class="fab fa-facebook fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://github.com/ctfd"><i class="fab fa-github fa-2x" aria-hidden="true"></i></a>
        </h3>
        <br>
        <h4 class="text-center">
            <a href="admin">Click here</a> to login and setup your CTF
        </h4>
    </div>
</div>""".format(
                request.script_root
            )

            page = Pages(title=None, route="index", content=index, draft=False)
            # Visibility
            set_config("challenge_visibility", "private")
            set_config("registration_visibility", "public")
            set_config("score_visibility", "public")
            set_config("account_visibility", "public")

            # Start time
            set_config("start", None)
            set_config("end", None)
            set_config("freeze", None)

            # Verify emails
            set_config("verify_emails", None)

            set_config("mail_server", None)
            set_config("mail_port", None)
            set_config("mail_tls", None)
            set_config("mail_ssl", None)
            set_config("mail_username", None)
            set_config("mail_password", None)
            set_config("mail_useauth", None)

            set_config("setup", True)

            try:
                db.session.add(admin)
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

            try:
                db.session.add(page)
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

            login_user(admin)

            db.session.close()
            app.setup = False
            with app.app_context():
                cache.clear()

            return redirect(url_for("views.static_html"))
        return render_template("setup.html", nonce=session.get("nonce"))
    return redirect(url_for("views.static_html"))


@views.route("/notifications", methods=["GET"])
def notifications():
    notifications = Notifications.query.order_by(Notifications.id.desc()).all()
    return render_template("notifications.html", notifications=notifications)


@views.route("/settings", methods=["GET"])
@authed_only
def settings():
    user = get_current_user()
    name = user.name
    email = user.email
    website = user.website
    affiliation = user.affiliation
    country = user.country
    prevent_name_change = get_config("prevent_name_change")
    confirm_email = get_config("verify_emails") and not user.verified
    return render_template(
        "settings.html",
        name=name,
        email=email,
        website=website,
        affiliation=affiliation,
        country=country,
        prevent_name_change=prevent_name_change,
        confirm_email=confirm_email,
    )


@views.route("/static/user.css")
def custom_css():
    """
    Custom CSS Handler route
    :return:
    """
    return Response(get_config("css"), mimetype="text/css")


@views.route("/", defaults={"route": "index"})
@views.route("/<path:route>")
def static_html(route):
    """
    Route in charge of routing users to Pages.
    :param route:
    :return:
    """
    page = get_page(route)
    if page is None:
        abort(404)
    else:
        if page.auth_required and authed() is False:
            return redirect(url_for("auth.login", next=request.full_path))

        return render_template("page.html", content=markdown(page.content))


@views.route("/files", defaults={"path": ""})
@views.route("/files/<path:path>")
def files(path):
    """
    Route in charge of dealing with making sure that CTF challenges are only accessible during the competition.
    :param path:
    :return:
    """
    f = Files.query.filter_by(location=path).first_or_404()
    if f.type == "challenge":
        if challenges_visible():
            if current_user.is_admin() is False:
                if not ctftime():
                    if ctf_ended() and view_after_ctf():
                        pass
                    else:
                        abort(403)
        else:
            if not ctftime():
                abort(403)

            # Allow downloads if a valid token is provided
            token = request.args.get("token", "")
            try:
                data = unserialize(token, max_age=3600)
                user_id = data.get("user_id")
                team_id = data.get("team_id")
                file_id = data.get("file_id")
                user = Users.query.filter_by(id=user_id).first()
                team = Teams.query.filter_by(id=team_id).first()

                # Check user is admin if challenge_visibility is admins only
                if (
                    get_config("challenge_visibility") == "admins"
                    and user.type != "admin"
                ):
                    abort(403)

                # Check that the user exists and isn't banned
                if user:
                    if user.banned:
                        abort(403)
                else:
                    abort(403)

                # Check that the team isn't banned
                if team:
                    if team.banned:
                        abort(403)
                else:
                    pass

                # Check that the token properly refers to the file
                if file_id != f.id:
                    abort(403)

            # The token isn't expired or broken
            except (BadTimeSignature, SignatureExpired, BadSignature):
                abort(403)

    uploader = get_uploader()
    try:
        return uploader.download(f.location)
    except IOError:
        abort(404)


@views.route("/themes/<theme>/static/<path:path>")
def themes(theme, path):
    """
    General static file handler
    :param theme:
    :param path:
    :return:
    """
    filename = safe_join(app.root_path, "themes", theme, "static", path)
    if os.path.isfile(filename):
        return send_file(filename)
    else:
        abort(404)

@views.route("/countdown")
def countdown_html():
    return render_template("countdown.html")

CTFd/themes/aperi/templates/users/private.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1 id="user-id" user-id="{{ user.id }}">{{ user.name }}</h1>

			{% if user.oauth_id %}
				<a href="https://majorleaguecyber.org/u/{{ user.name }}">
					<h3><span class="badge badge-primary">Official</span></h3>
				</a>
			{% endif %}

			{% if user.affiliation %}
				<h3><span class="badge badge-primary">{{ user.affiliation }}</span></h3>
			{% endif %}

			<div class="user-info">
				<h2 id="user-place" class="text-center">
					{# This intentionally hides the user's place because this can be their internal profile. #}
					{# Public page hiding is done at the route level #}
					{% if scores_visible() %}
						Place N° {{ user.place | string | replace("st","") | replace("nd","") | replace("rd","") | replace("th","") }}
					{% endif %}
				</h2>
				<h2 id="user-score" class="text-center">
					{% if score %}
						{{ user.score }}
						<small>points</small>
					{% endif %}
				</h2>
			</div>

			<div class="pt-3">
				{% if user.website and (user.website.startswith('http://') or user.website.startswith('https://')) %}
					<a href="{{ user.website }}" target="_blank" style="color: inherit;">
						<i class="fas fa-external-link-alt fa-2x px-2" data-toggle="tooltip" data-placement="top"
						   title="{{ user.website }}"></i>
					</a>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="container">
		{% if errors %}
			<div id='errors' class="row">
				{% for error in errors %}
					<h1>{{ error }}</h1>
				{% endfor %}
			</div>
		{% else %}

			{% if score_frozen %}
				<div class="row">
					<h1 class="text-center">Le classement a été figé.</h1>
				</div>
			{% endif %}

			<br>

			{% set solves = user.solves %}
			{% set awards = user.awards %}

			{% if solves %}
	        <br><div style="display: inline-block;width:50%;vertical-align:top;"><canvas id="failChart" height="200px"></canvas></div><!--
	        --><div style="display: inline-block;width:50%;vertical-align:top;"><canvas id="challChart" height="200px"></canvas></div><br>
	        <div style="margin-top:70px;height: 410px;"><canvas id="scoreChart" width="400" height="150px"></canvas></div><br/>
	        <div class="clearfix"></div>


				{% if awards %}
					<div class="row">
						<div class="col-md-12">
							<h3>Récompenses</h3>
						</div>
						{% for award in awards %}
							<div class="col-md-3 col-sm-6">
								<p class="text-center"><strong>{{ award.name }}</strong></p>
								{% if award.category %}<p class="text-center">{{ award.category }}</p>{% endif %}
								{% if award.description %}<p class="text-center">{{ award.description }}</p>{% endif %}
								<p class="text-center">{{ award.value }}</p>
							</div>
						{% endfor %}
					</div>

					<br>
				{% endif %}

				<div class="row">
					<div class="col-md-12">
						<h3>Résolutions</h3>
						<table class="table table-striped">
							<thead>
							<tr>
								<td><b>Challenge</b></td>
								<td class="d-none d-md-block d-lg-block"><b>Categorie</b></td>
								<td><b>Valeur</b></td>
								<td><b>Temps</b></td>
							</tr>
							</thead>
							<tbody>
							{% for solve in solves %}
								<tr>
									<td>
										<a href="{{ url_for('challenges.listing') }}#{{ solve.challenge.name }}">{{ solve.challenge.name }}</a>
									</td>
									<td class="d-none d-md-block d-lg-block">{{ solve.challenge.category }}</td>
									<td>{{ solve.challenge.value }}</td>
									<td class="solve-time">
										<script>document.write(moment("{{ solve.date|isoformat }}").local("fr").format('DD/MM/YYYY - hh:mm:ss'))</script>
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			{% else %}
				<div class="text-center"><h3 class="spinner-error">Pas de résolution pour le moment.</h3></div>
			{% endif %}
		{% endif %}
	</div>
{% endblock %}

{% block scripts %}
	<script>
        var user_id = {{ user.id }};
        var user_name = {{ user.name | tojson }};
        var team_id = {{ user.team_id | tojson }};
        var user_self = {{ (user.id == id) | tojson }};
        var user_account_id = user_self ? "me" : user_id;
	</script>
	<script src="{{ url_for('views.themes', path='js/Chart.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/Chart.bundle.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/utils.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/user.js') }}"></script>
{% endblock %}

CTFd/themes/aperi/templates/users/public.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1 id="user-id" user-id="{{ user.id }}">{{ user.name }}</h1>

			{% if user.oauth_id %}
				<a href="https://majorleaguecyber.org/u/{{ user.name }}">
					<h3><span class="badge badge-primary">Official</span></h3>
				</a>
			{% endif %}

			{% if user.affiliation %}
				<h3><span class="badge badge-primary">{{ user.affiliation }}</span></h3>
			{% endif %}

			<div class="user-info">
				<h2 id="user-place" class="text-center">
					{# This intentionally hides the user's place because this can be their internal profile. #}
					{# Public page hiding is done at the route level #}
					{% if scores_visible() %}
						Place N° {{ user.place | string | replace("st","") | replace("nd","") | replace("rd","") | replace("th","") }}
					{% endif %}
				</h2>
				<h2 id="user-score" class="text-center">
					{% if score %}
						{{ user.score }}
						<small>points</small>
					{% endif %}
				</h2>
			</div>
		</div>
	</div>
	<div class="container">
		{% if errors %}
			<div id='errors' class="row">
				{% for error in errors %}
					<h1>{{ error }}</h1>
				{% endfor %}
			</div>
		{% else %}

			{% if score_frozen %}
				<div class="row">
					<h1 class="text-center">Le classement a été figé.</h1>
				</div>
			{% endif %}

			<br>

			{% set solves = user.solves %}
			{% set awards = user.awards %}

			{% if solves %}
	        <br><div style="display: inline-block;width:50%;vertical-align:top;"><canvas id="failChart" height="200px"></canvas></div><!--
	        --><div style="display: inline-block;width:50%;vertical-align:top;"><canvas id="challChart" height="200px"></canvas></div><br>
	        <div style="margin-top:70px;height: 410px;"><canvas id="scoreChart" width="400" height="150px"></canvas></div><br/>
	        <div class="clearfix"></div>

				{% if awards %}
					<div class="row">
						<div class="col-md-12">
							<h3>Récompenses</h3>
						</div>
						{% for award in awards %}
							<div class="col-md-3 col-sm-6">
								<p class="text-center"><strong>{{ award.name }}</strong></p>
								{% if award.category %}<p class="text-center">{{ award.category }}</p>{% endif %}
								{% if award.description %}<p class="text-center">{{ award.description }}</p>{% endif %}
								<p class="text-center">{{ award.value }}</p>
							</div>
						{% endfor %}
					</div>

					<br>
				{% endif %}

				<div class="row">
					<div class="col-md-12">
						<h3>Résolutions</h3>
						<table class="table table-striped">
							<thead>
							<tr>
								<td><b>Challenge</b></td>
								<td class="d-none d-md-block d-lg-block"><b>Categorie</b></td>
								<td><b>Valeur</b></td>
								<td><b>Temps</b></td>
							</tr>
							</thead>
							<tbody>
							{% for solve in solves %}
								<tr>
									<td>
										<a href="{{ url_for('challenges.listing') }}#{{ solve.challenge.name }}">{{ solve.challenge.name }}</a>
									</td>
									<td class="d-none d-md-block d-lg-block">{{ solve.challenge.category }}</td>
									<td>{{ solve.challenge.value }}</td>
									<td class="solve-time">
										<script>document.write(moment("{{ solve.date|isoformat }}").local("fr").format('DD/MM/YYYY - hh:mm:ss'))</script>
									</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			{% else %}
				<div class="text-center"><h3 class="spinner-error">Pas de résolution pour le moment.</h3></div>
			{% endif %}
		{% endif %}
	</div>
{% endblock %}

{% block scripts %}
	<script>
        var user_id = {{ user.id }};
        var user_name = {{ user.name | tojson }};
        var team_id = {{ user.team_id | tojson }};
        var user_self = {{ (user.id == id) | tojson }};
        var user_account_id = user_self ? "me" : user_id;
	</script>
	<script src="{{ url_for('views.themes', path='js/Chart.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/Chart.bundle.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/utils.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/user.js') }}"></script>
{% endblock %}

CTFd/themes/aperi/templates/users/user.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1 id="user-id" user-id="{{ user.id }}">{{ user.name }}</h1>

		{% if user.oauth_id %}
			<a href="https://majorleaguecyber.org/u/{{ user.name }}">
				<h3><span class="badge badge-primary">Official</span></h3>
			</a>
		{% endif %}

		<div class="user-info">
			<h2 id="user-place" class="text-center">
				{# This intentionally hides the user's place because this can be their internal profile. #}
				{# Public page hiding is done at the route level #}
				{% if scores_visible() %}
					{{ user.place }}
					<small>place</small><!--
				-->{% endif %}
				{% if score %}<!--
					-->&nbsp;-&nbsp;{{ user.score }}
					<small>points</small>
				{% endif %}
			</h2>
		</div>
	</div>
</div>
<div class="container">
	{% if errors %}
	<div id='errors' class="row">
	{% for error in errors %}
		<h1>{{ error }}</h1>
	{% endfor %}
	</div>
	{% else %}

	{% if score_frozen %}
	<div class="row">
		<h1 class="text-center">Le classement a été figé.</h1>
	</div>
	{% endif %}

	<br>

	{% set solves = user.solves %}
	{% set awards = user.awards %}

	{% if solves %}
	<div id="keys-pie-graph" class="w-50 mr-0 pr-0 float-left d-none d-md-block d-lg-block">
		<div class="text-center">
			<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
		</div>
	</div>
	<div id="categories-pie-graph" class="w-50 mr-0 pr-0 float-left d-none d-md-block d-lg-block">
		<div class="text-center">
			<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
		</div>
	</div>
	<br class="clearfix">
	<div id="score-graph" class="w-100 float-right d-none d-md-block d-lg-block">
		<div class="text-center">
			<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
		</div>
	</div>

	<div class="clearfix"></div>

	{% if awards %}
	<div class="row">
		<div class="col-md-12">
			<h3>Récompenses</h3>
		</div>
		{% for award in awards %}
				<div class="col-md-3 col-sm-6">
					<p class="text-center"><strong>{{ award.name }}</strong></p>
					{% if award.category %}<p class="text-center">{{ award.category }}</p>{% endif %}
					{% if award.description %}<p class="text-center">{{ award.description }}</p>{% endif %}
					<p class="text-center">{{ award.value }}</p>
				</div>
		{% endfor %}
	</div>

	<br>
	{% endif %}

	<div class="row">
		<div class="col-md-12">
			<h3>Flags</h3>
			<table class="table table-striped">
				<thead>
					<tr>
						<td><b>Challenge</b></td>
						<td class="d-none d-md-block d-lg-block"><b>Catégorie</b></td>
						<td><b>Valeur</b></td>
						<td><b>Temps</b></td>
					</tr>
				</thead>
				<tbody>
				{% for solve in solves %}
					<tr>
						<td><a href="{{ url_for('challenges.listing') }}#{{ solve.challenge.name }}">{{ solve.challenge.name }}</a></td>
						<td class="d-none d-md-block d-lg-block">{{ solve.challenge.category }}</td><td>{{ solve.challenge.value }}</td>
						<td class="solve-time"><script>document.write( moment("{{ solve.date|isoformat }}").local().format('MMMM Do, h:mm:ss A'))</script></td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	{% else %}
		<div class="text-center"><h3 class="spinner-error">Pas encore de flag</h3></div>
	{% endif %}
	{% endif %}
</div>
{% endblock %}

{% block scripts %}
	<script>
	var user_id = {{ user.id }};
	var user_name = {{ user.name | tojson }};
	var team_id = {{ user.team_id | tojson }};
	var user_self = {{ (user.id == id) | tojson }};
	var user_account_id = user_self ? "me" : user_id;
	</script>
	<script src="{{ url_for('views.themes', path='js/vendor/plotly.min.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/utils.js') }}"></script>
	<script src="{{ url_for('views.themes', path='js/user.js') }}"></script>
{% endblock %}

CTFd/themes/aperi/templates/users/users.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Joueurs</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<table class="table table-striped">
					<thead>
					<tr>
						<td><b>Pseudo</b></td>
						<td><b>Site web</b></td>
						<td class="d-none d-md-table-cell d-lg-table-cell"><b>Affiliation</b></td>
						<td class="d-none d-md-table-cell d-lg-table-cell"><b>Pays</b></td>
					</tr>
					</thead>
					<tbody>
					{% for user in users %}
						<tr>
							<td>
								{% if scores_visible() %}
									<a href="{{ url_for('users.public', user_id=user.id) }}">
										{{ user.name | truncate(50) }}
									</a>
								{% else %}
									<span>{{ user.name | truncate(50) }}</span>
								{% endif %}
								{% if user.oauth_id %}
									<a href="https://majorleaguecyber.org/u/{{ user.name }}">
										<span class="badge badge-primary">Official</span>
									</a>
								{% endif %}
							</td>
							<td class="text-center" style="width: 10px;">
								{% if user.website and (user.website.startswith('http://') or user.website.startswith('https://')) %}
									<a href="{{ user.website }}" target="_blank">
										<i class="fas fa-external-link-alt" data-toggle="tooltip" data-placement="top"
										   title="{{ user.website }}"></i>
									</a>
								{% endif %}
							</td>
							<td class="d-none d-md-table-cell d-lg-table-cell">
								{% if user.affiliation %}
									{% if user.affiliation | length > 50 %}
										<span data-toggle="tooltip" data-placement="top" title="{{ user.affiliation }}">
									{% if user.affiliation %}{{ user.affiliation | truncate(50) }}{% endif %}
								</span>
									{% else %}
										<span>
									{% if user.affiliation %}{{ user.affiliation | truncate(50) }}{% endif %}
								</span>
									{% endif %}
								{% endif %}
							</td>
							<td class="d-none d-md-table-cell d-lg-table-cell">
								<span>{% if user.country %}{{ lookup_country_code(user.country) }}{% endif %}</span>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		{% if pages > 1 %}
			<div class="row">
				<div class="col-md-12">
					<div class="text-center">Page
						<br>
						{% if curr_page != 1 %}
							<a href="{{ url_for('users.listing', page=curr_page - 1) }}">
								&lt;&lt;&lt;
							</a>
						{% endif %}
						{% for page in range(1, pages + 1) %}
							{% if curr_page != page %}
								<a href="{{ url_for('users.listing', page=page) }}">{{ page }}</a>
							{% else %}
								<b>{{ page }}</b>
							{% endif %}
						{% endfor %}
						{% if curr_page != pages %}
							<a href="{{ url_for('users.listing', page=curr_page + 1) }}">
								&gt;&gt;&gt;
							</a>
						{% endif %}
					</div>
				</div>
			</div>
		{% endif %}
	</div>
{% endblock %}

{% block scripts %}
{% endblock %}